name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v1.3.0
        with:
          deno-version: v1.0.0-rc1

      - name: Check formatting
        run: deno fmt --check

      - name: Run unit tests
        run: deno test src/

      - name: Start rabbitmq
        uses: lenkan/rabbitmq-action@v1.1.0
        with:
          rabbitmq version: "3-management"

      - name: Wait for rabbit
        run: deno run --allow-net module_test/wait_for_server.ts

      - name: Run module tests
        run: deno test --allow-net module_test/
